In [1]:

import pandas as pd
df= pd.read_csv(r'D:\files\chrome_reviews.csv') #importing data

In [2]:
df.head()

,ID,Review URL,Text,Star,Thumbs Up,User Name,Developer Reply,Version,Review Date,App ID
0,3886,https://play.google.com/store/apps/details?id=...,This is very helpfull aap.,5,0,INDIAN Knowledge,NaN,83.0.4103.106,2020-12-19,com.android.chrome
1,3887,https://play.google.com/store/apps/details?id=...,Good,3,2,Ijeoma Happiness,NaN,85.0.4183.127,2020-12-19,com.android.chrome
2,3888,https://play.google.com/store/apps/details?id=...,Not able to update. Neither able to uninstall.,1,0,Priti D BtCFs-29,NaN,85.0.4183.127,2020-12-19,com.android.chrome
3,3889,https://play.google.com/store/apps/details?id=...,Nice app,4,0,Ajeet Raja,NaN,77.0.3865.116,2020-12-19,com.android.chrome
4,3890,https://play.google.com/store/apps/details?id=...,Many unwanted ads,1,0,Rams Mp,NaN,87.0.4280.66,2020-12-19,com.android.chrome

In [3]:
df = df.drop(['ID','Review URL','Thumbs Up','User Name','Developer Reply',
                 'Version', 'Review Date', 'App ID'], axis=1)  #droping necessary columns

In [4]:
df.head()

                                             Text  Star
0                      This is very helpfull aap.     5
1                                            Good     3
2  Not able to update. Neither able to uninstall.     1
3                                        Nice app     4
4                               Many unwanted ads     1

In [5]:
import re

In [6]:
df['review']=df['Text'].apply(lambda x:re.sub('[^A-Za-z0-9]+', ' ', str(x)))  #removing punctuation sign and emojis

In [7]:
df.head()

,Text,Star,review
0,This is very helpfull aap.,5,This is very helpfull aap
1,Good,3,Good
2,Not able to update. Neither able to uninstall.,1,Not able to update Neither able to uninstall
3,Nice app,4,Nice app
4,Many unwanted ads,1,Many unwanted ads

In [8]:
df.tail()

,Text,Star,review
7199,Bagusss..,5,Bagusss
7200,Bad version 😔,1,Bad version
7201,One thing that I have to say I can't spelled t...,5,One thing that I have to say I can t spelled t...
7202,Excellent,5,Excellent
7203,After update it lag and always slow same goes ...,1,After update it lag and always slow same goes ...

In [9]:
df['review']=df['review'].str.lower()       #converting capital letters to small letters

In [10]:
df.head()

,Text,Star,review
0,This is very helpfull aap.,5,this is very helpfull aap
1,Good,3,good
2,Not able to update. Neither able to uninstall.,1,not able to update neither able to uninstall
3,Nice app,4,nice app
4,Many unwanted ads,1,many unwanted ads

In [11]:
import nltk.corpus

In [12]:
from nltk.corpus import stopwords

In [13]:
stop=stopwords.words('english')         #creating instance for removing unnecessary words

In [14]:

df['streview'] = df['review'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [32]:
df.head()

,Text,Star,review,streview
0,This is very helpfull aap.,5,this is very helpfull aap,helpfull aap
1,Good,3,good,good
2,Not able to update. Neither able to uninstall.,1,not able to update neither able to uninstall,able update neither able uninstall
3,Nice app,4,nice app,nice app
4,Many unwanted ads,1,many unwanted ads,many unwanted ads

In [31]:
df.tail()

,Text,Star,review,streview
7199,Bagusss..,5,bagusss,bagusss
7200,Bad version 😔,1,bad version,bad version
7201,One thing that I have to say I can't spelled t...,5,one thing that i have to say i can t spelled t...,one thing say spelled good problem try spell best
7202,Excellent,5,excellent,excellent
7203,After update it lag and always slow same goes ...,1,after update it lag and always slow same goes ...,update lag always slow goes googleee want work

In [17]:
from textblob import TextBlob

In [18]:
def getPolarity(review):
    return TextBlob(review).sentiment.polarity    #checking polarity

In [19]:
def analysis(score):
    if score < 0:
        return 'Negative'
    elif score == 0:
        return 'Neutral'
    else:
        return 'Positive'

In [20]:
my_data = pd.DataFrame(df[['Text','Star','streview']])

In [21]:
my_data['Polarity'] = my_data['streview'].apply(getPolarity) 
my_data['Analysis'] = my_data['Polarity'].apply(analysis)

In [22]:
my_data.head()

,Text,Star,streview,Polarity,Analysis
0,This is very helpfull aap.,5,helpfull aap,0.0,Neutral
1,Good,3,good,0.7,Positive
2,Not able to update. Neither able to uninstall.,1,able update neither able uninstall,0.5,Positive
3,Nice app,4,nice app,0.6,Positive
4,Many unwanted ads,1,many unwanted ads,0.5,Positive

In [23]:
my_data.tail()

,Text,Star,streview,Polarity,Analysis
7199,Bagusss..,5,bagusss,0.00,Neutral
7200,Bad version 😔,1,bad version,-0.70,Negative
7201,One thing that I have to say I can't spelled t...,5,one thing say spelled good problem try spell best,0.85,Positive
7202,Excellent,5,excellent,1.00,Positive
7203,After update it lag and always slow same goes ...,1,update lag always slow goes googleee want work,-0.30,Negative

In [24]:
m_data=my_data.loc[my_data['Analysis'] == 'Positive']     #selecting positive reviews

In [25]:
m_data.head()

,Text,Star,streview,Polarity,Analysis
1,Good,3,good,0.7,Positive
2,Not able to update. Neither able to uninstall.,1,able update neither able uninstall,0.5,Positive
3,Nice app,4,nice app,0.6,Positive
4,Many unwanted ads,1,many unwanted ads,0.5,Positive
5,This app good,4,app good,0.7,Positive

In [27]:
dt=m_data.loc[m_data['Star']<3]

In [29]:
dt=dt.drop(['streview','Polarity','Analysis'],axis=1)

In [30]:
dt     #reviews which are possibly positive but rating is negative

                                                   Text  Star
2        Not able to update. Neither able to uninstall.     1
4                                     Many unwanted ads     1
9     Many times I tried to update its not updating....     1
12    App is not getting update and it is not gettin...     1
15                Very coming in real status. Thank you     1
...                                                 ...   ...
7094                       Not able to update this app.     1
7147  I'm not able to update the app for some reason...     2
7151                            No good its not updated     1
7170                                 Not able to update     1
7195  Chrome is good, I trust this update will make ...     1

[595 rows x 2 columns]